name: LIFE LANGUAGE BOOTCAMP
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27462
title: LifeLanguage Bootcamp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0a0a0a'
    - '#c0b49c'
    - '#8e0a17'
    - '#898c83'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
