name: LIFE LANGUAGE BOOTCAMP
favicon: null
layout_spectrum: 0.8220072840340436
typography_spectrum: 0.016537661897018552
title: LifeLanguage Bootcamp
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0a0a0a'
    - '#c0b49c'
    - '#8e0a17'
    - '#898c83'
  brandStrength: 0.125
  lightness: 0.6727914016228169
  saturation: 0.4618310718797147
  rhythmicContrast: 0.8449451541528106
purpose: []
